/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EducationRouteImport } from './routes/education'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'
import { Route as ApiPublicRouteImport } from './routes/api.public'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as AdminTechnologiesRouteImport } from './routes/admin.technologies'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminEducationRouteImport } from './routes/admin.education'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as ApiAdminUploadRouteImport } from './routes/api.admin.upload'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'

const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoute = ApiPublicRouteImport.update({
  id: '/api/public',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTechnologiesRoute = AdminTechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEducationRoute = AdminEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiAdminRoute,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ApiAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/technologies': typeof TechnologiesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/technologies': typeof AdminTechnologiesRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/public': typeof ApiPublicRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/login': typeof LoginRoute
  '/technologies': typeof TechnologiesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/technologies': typeof AdminTechnologiesRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/public': typeof ApiPublicRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/technologies': typeof TechnologiesRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/technologies': typeof AdminTechnologiesRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/public': typeof ApiPublicRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/certificates'
    | '/education'
    | '/experience'
    | '/login'
    | '/projects'
    | '/technologies'
    | '/admin/certificates'
    | '/admin/education'
    | '/admin/jobs'
    | '/admin/projects'
    | '/admin/technologies'
    | '/api/admin'
    | '/api/public'
    | '/api/resume-chat'
    | '/projects/$projectId'
    | '/admin/'
    | '/projects/'
    | '/api/admin/login'
    | '/api/admin/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certificates'
    | '/education'
    | '/experience'
    | '/login'
    | '/technologies'
    | '/admin/certificates'
    | '/admin/education'
    | '/admin/jobs'
    | '/admin/projects'
    | '/admin/technologies'
    | '/api/admin'
    | '/api/public'
    | '/api/resume-chat'
    | '/projects/$projectId'
    | '/admin'
    | '/projects'
    | '/api/admin/login'
    | '/api/admin/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/certificates'
    | '/education'
    | '/experience'
    | '/login'
    | '/projects'
    | '/technologies'
    | '/admin/certificates'
    | '/admin/education'
    | '/admin/jobs'
    | '/admin/projects'
    | '/admin/technologies'
    | '/api/admin'
    | '/api/public'
    | '/api/resume-chat'
    | '/projects/$projectId'
    | '/admin/'
    | '/projects/'
    | '/api/admin/login'
    | '/api/admin/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertificatesRoute: typeof CertificatesRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TechnologiesRoute: typeof TechnologiesRoute
  ApiAdminRoute: typeof ApiAdminRouteWithChildren
  ApiPublicRoute: typeof ApiPublicRoute
  ApiResumeChatRoute: typeof ApiResumeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public': {
      id: '/api/public'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/technologies': {
      id: '/admin/technologies'
      path: '/technologies'
      fullPath: '/admin/technologies'
      preLoaderRoute: typeof AdminTechnologiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/education': {
      id: '/admin/education'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminEducationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof ApiAdminRoute
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof ApiAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminEducationRoute: typeof AdminEducationRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTechnologiesRoute: typeof AdminTechnologiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminEducationRoute: AdminEducationRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTechnologiesRoute: AdminTechnologiesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ApiAdminRouteChildren {
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

const ApiAdminRouteChildren: ApiAdminRouteChildren = {
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}

const ApiAdminRouteWithChildren = ApiAdminRoute._addFileChildren(
  ApiAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CertificatesRoute: CertificatesRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  TechnologiesRoute: TechnologiesRoute,
  ApiAdminRoute: ApiAdminRouteWithChildren,
  ApiPublicRoute: ApiPublicRoute,
  ApiResumeChatRoute: ApiResumeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
